from PyQt5 import QtCore, QtGui, QtWidgets


class Screen(object):
    def __init__(self):
        self.HLayout = None
        self.question_left = None
        self.score = None
        self.result = None
        self.menu_btn = None
        self.result_page = None
        self.horizontalLayoutWidget = None
        self.wrong_btn = None
        self.question_area = None
        self.right_btn = None
        self.play_page = None
        self.categories = None
        self.searching = None
        self.number_question = None
        self.difficulties = None
        self.category = None
        self.difficulty = None
        self.number = None
        self.play = None
        self.main_label = None
        self.main_page = None
        self.stackedWidget = None
        self.centralwidget = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setFixedSize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.stackedWidget.setStyleSheet("#main_page, #play_page, #result_page {background-color: rgb(20, 100, 200);}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_page = QtWidgets.QWidget()
        self.main_page.setStyleSheet("")
        self.main_page.setObjectName("main_page")
        self.main_label = QtWidgets.QLabel(self.main_page)
        self.main_label.setGeometry(QtCore.QRect(0, 20, 801, 221))
        font = QtGui.QFont()
        font.setFamily("Ink Free")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.main_label.setFont(font)
        self.main_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.main_label.setAlignment(QtCore.Qt.AlignCenter)
        self.main_label.setObjectName("main_label")
        self.play = QtWidgets.QPushButton(self.main_page)
        self.play.setGeometry(QtCore.QRect(150, 480, 509, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play.sizePolicy().hasHeightForWidth())
        self.play.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ink Free")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.play.setFont(font)
        self.play.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.play.setStyleSheet("color: rgb(0, 54, 126);")
        self.play.setObjectName("play")
        self.number = QtWidgets.QLabel(self.main_page)
        self.number.setGeometry(QtCore.QRect(150, 370, 509, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.number.sizePolicy().hasHeightForWidth())
        self.number.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ink Free")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.number.setFont(font)
        self.number.setStyleSheet("color: rgb(255, 255, 255);")
        self.number.setAlignment(QtCore.Qt.AlignCenter)
        self.number.setObjectName("number")
        self.difficulty = QtWidgets.QLabel(self.main_page)
        self.difficulty.setGeometry(QtCore.QRect(150, 290, 509, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.difficulty.sizePolicy().hasHeightForWidth())
        self.difficulty.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ink Free")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.difficulty.setFont(font)
        self.difficulty.setStyleSheet("color: rgb(255, 255, 255);")
        self.difficulty.setAlignment(QtCore.Qt.AlignCenter)
        self.difficulty.setObjectName("difficulty")
        self.category = QtWidgets.QLabel(self.main_page)
        self.category.setGeometry(QtCore.QRect(150, 206, 509, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category.sizePolicy().hasHeightForWidth())
        self.category.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ink Free")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.category.setFont(font)
        self.category.setStyleSheet("color: rgb(255, 255, 255);")
        self.category.setAlignment(QtCore.Qt.AlignCenter)
        self.category.setObjectName("category")
        self.number_question = QtWidgets.QComboBox(self.main_page)
        self.number_question.setGeometry(QtCore.QRect(150, 400, 511, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.number_question.setFont(font)
        self.number_question.setStyleSheet("color: rgb(7, 39, 143);")
        self.number_question.setObjectName("number_question")
        self.number_question.addItem("")
        self.number_question.setItemText(0, "")
        self.difficulties = QtWidgets.QComboBox(self.main_page)
        self.difficulties.setGeometry(QtCore.QRect(150, 320, 511, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.difficulties.setFont(font)
        self.difficulties.setStyleSheet("color: rgb(7, 39, 143);")
        self.difficulties.setObjectName("difficulties")
        self.difficulties.addItem("")
        self.categories = QtWidgets.QComboBox(self.main_page)
        self.categories.setGeometry(QtCore.QRect(152, 240, 511, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.categories.setFont(font)
        self.categories.setStyleSheet("color: rgb(7, 39, 143);")
        self.categories.setObjectName("categories")
        self.categories.addItem("")
        self.searching = QtWidgets.QLabel(self.main_page)
        self.searching.setGeometry(QtCore.QRect(150, 450, 511, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.searching.setFont(font)
        self.searching.setStyleSheet("color: rgb(255, 255, 255);")
        self.searching.setAlignment(QtCore.Qt.AlignCenter)
        self.searching.setObjectName("searching")
        self.stackedWidget.addWidget(self.main_page)
        self.play_page = QtWidgets.QWidget()
        self.play_page.setObjectName("play_page")
        self.right_btn = QtWidgets.QPushButton(self.play_page)
        self.right_btn.setGeometry(QtCore.QRect(670, 100, 71, 351))
        self.right_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.right_btn.setStyleSheet("QPushButton {\n"
                                     "background-color: rgb(0, 230, 0);\n"
                                     "border-radius: 20px;\n"
                                     "border: 3px solid rgb(0, 240, 0);\n"
                                     "}\n"
                                     "QPushButton:hover {\n"
                                     "background-color: rgb(0, 240, 0);\n"
                                     "border: 3px solid rgb(0, 255, 0);\n}")
        self.right_btn.setText("")
        self.right_btn.setObjectName("right_btn")
        self.question_area = QtWidgets.QLabel(self.play_page)
        self.question_area.setGeometry(QtCore.QRect(140, 100, 521, 351))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.question_area.setFont(font)
        self.question_area.setStyleSheet("background-color: rgb(255, 255, 255);\nborder-radius: 20px;"
                                         "\npadding: 20px 20px;")
        self.question_area.setText("")
        self.question_area.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.question_area.setWordWrap(True)
        self.question_area.setObjectName("question_area")
        self.wrong_btn = QtWidgets.QPushButton(self.play_page)
        self.wrong_btn.setGeometry(QtCore.QRect(62, 100, 71, 351))
        self.wrong_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.wrong_btn.setStyleSheet("QPushButton {\n"
                                     "background-color: rgb(230, 0, 0);\n"
                                     "border-radius: 20px;\n"
                                     "border: 3px solid rgb(240, 0, 0);\n"
                                     "}\n"
                                     "QPushButton:hover {\n"
                                     "background-color: rgb(240, 0, 0);\n"
                                     "border: 3px solid rgb(255, 0, 0);\n}")
        self.wrong_btn.setText("")
        self.wrong_btn.setObjectName("wrong_btn")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.play_page)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(140, 460, 521, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.HLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.HLayout.setContentsMargins(0, 0, 0, 0)
        self.HLayout.setObjectName("HLayout")
        self.question_left = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.question_left.setFont(font)
        self.question_left.setStyleSheet("color: rgb(255, 255, 255);")
        self.question_left.setAlignment(QtCore.Qt.AlignCenter)
        self.question_left.setObjectName("question_left")
        self.HLayout.addWidget(self.question_left)
        self.score = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.score.setFont(font)
        self.score.setStyleSheet("color: rgb(255, 255, 255);")
        self.score.setAlignment(QtCore.Qt.AlignCenter)
        self.score.setObjectName("score")
        self.HLayout.addWidget(self.score)
        self.stackedWidget.addWidget(self.play_page)
        self.result_page = QtWidgets.QWidget()
        self.result_page.setObjectName("result_page")
        self.result = QtWidgets.QLabel(self.result_page)
        self.result.setGeometry(QtCore.QRect(0, 150, 801, 181))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(37)
        font.setBold(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setStyleSheet("color: rgb(255, 255, 255);")
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setObjectName("result")
        self.menu_btn = QtWidgets.QPushButton(self.result_page)
        self.menu_btn.setGeometry(QtCore.QRect(310, 410, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Ink Free")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.menu_btn.setFont(font)
        self.menu_btn.setStyleSheet("color: rgb(0, 54, 126);")
        self.menu_btn.setObjectName("menu_btn")
        self.stackedWidget.addWidget(self.result_page)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Test Your Knowledge"))
        self.main_label.setText(_translate("MainWindow", "TEST YOUR KNOWLEDGE"))
        self.play.setText(_translate("MainWindow", "PLAY"))
        self.number.setText(_translate("MainWindow", "Number of Questions"))
        self.difficulty.setText(_translate("MainWindow", "Choose Difficulty"))
        self.category.setText(_translate("MainWindow", "Choose Category"))
        self.difficulties.setItemText(0, _translate("MainWindow", "Any Difficulty"))
        self.categories.setItemText(0, _translate("MainWindow", "Any Category"))
        self.number_question.setItemText(0, _translate("MainWindow", "1"))
        self.searching.setText(_translate("MainWindow", ""))
        self.question_left.setText(_translate("MainWindow", "Questions: (1/1)"))
        self.score.setText(_translate("MainWindow", "Score: (0)"))
        self.result.setText(_translate("MainWindow", "Quiz is Over!\nYour Score is: x/100"))
        self.menu_btn.setText(_translate("MainWindow", "Main Menu"))
